### PR TITLE
feat: Add pagination to resources List Closes #1

### LINKED ISSUE #1: FUTURE: paginate resources

### PR DESCRIPTION
**Pull request by Emmo00**
Added Pagination. Closes #1 

You can change to number of resources per page by editing the value of the `perPage` variable in `HomeView.vue` file

### CODE REVIEW

**Comment by Emmo00** [comment]
btw, this is the first time I'm writing tailwind. 😂

**Comment by lennyAiko** [comment]
Not bad for first time with tailwind though. I guess it was pretty fun.

Could you share an image or video of how the pagination works on your machine?

**Comment by Emmo00** [comment]
https://github.com/lennyAiko/ih-wiki/assets/88244468/2b4079ec-5e0e-4071-9005-33d922801acb

**Comment by Emmo00** [comment]
here @lennyAiko

**Comment by lennyAiko** [comment]
Awesome! However I want you to own this feature so I will just make some suggestions instead of doing it myself.

- Let's change the Previous and Next to icons.
- Instead of `page 1 of 6` we could do `1 / 6` or `1 of 6`.
- on mobile let it scroll to top when it has gotten to the next page. You can add this to the function:
```js
function scrollToTop() {
    window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
}
```
- We can have like 12 items on each screen, then maybe 8 on mobile if possible.
- Pagination buttons should only show only when another screen is available.

Thanks for the PR, if you need any support please let me know. I can also merge then carry on from here if you need me to.

I appreciate the effort

**Pull request merged**
